# -*- coding: utf-8 -*-
"""HW

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x_cvN1ygjhJnL4FA0X93DsTUg6YE58Oz
"""

a=input("Enter your repeating letters")
b=set(a)
c=list(b)
for i in c:
  print(i,end="")